# Generated by Django 5.1.2 on 2024-11-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0004_subscribers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AddField(
            model_name="post",
            name="youtube_url",
            field=models.URLField(null=True),
        ),
    ]
